map_to_negativize(source_array)
map_to_no_change(source_array)
map_to_double(source_array)
map_to_square(source_array)

reduce_to_total(source_array, starting_point)
reduce_to_all_true(source_array)
reduce_to_any_true(source_array)